import React from "react";
import Head from "next/head";

import Home from "../components/Home/Home";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Kurd Job</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  );
};

export default HomePage;
